### ISSUE TITLE
Questions about this program.

### ISSUE THREAD

**Issue by YuanYeshang** [minhnhatvt/label-distribution-learning-fer-tf#1]
I want to know why the input size of resnet-50 is 112*112 and not 224*224? Isn't it inconsistent with the paper? And what do you mean config_resnet18_affnet. Does it mean i need to use this file to train the model on affnet?

**Comment by minhnhatvt** [comment]
Hello Yuan, sorry for the late reply. We trained the resnet50 version with the 112x112 res for lighter and faster inference, which was used in our realtime demo. However, we found the model performance differences between these two settings are just negligible, while the speed is about 3x faster.

The "config_resnet18_affnet" is the model config we used for training on affectnet. You can experiment with these settings (e.g., backbone, lr,....) if you want. To train on affnet, you will also need an additional preprocessing step to obtain the .csv annotation file similar to raf data (which we unfortunately cannot provide here due to the license of the dataset). The file structured is decribed here: https://github.com/minhnhatvt/label-distribution-learning-fer-tf#datasets

**Comment by YuanYeshang** [comment]
Thank you for your reply, my previous doubts have disappeared. I'm using  "config_resnet18_affnet"  to train the model on affectnet. Now, it is in the 42nd epoch while the accuracy is about 64.86%. So will the accuracy be about 66.23% which you mentioned in the article when the epoch is up to 60?

**Comment by minhnhatvt** [comment]
I'm just not sure about this, if i remember correctly, the accuracy was obtained after around 20 epoch and it was the resnet50 model. The resnet18 accuracy is slightly lower. I think it may also depend on the method you used to align the face images (because the original faces' orientation of affectnet are not aligned/cropped properly). We used retinaface to predict the landmarks and rotate the (2D) face image  to the cannonical/portrait pose.

**Comment by YuanYeshang** [comment]
Well, I just thought the images of affectnet are aligned already. LOL. So your result was based on resnet50 and your affectnet was aligned, right?

**Comment by minhnhatvt** [comment]
Yes, i guess the key here is the face alignment. And I think it also depend on the machine and other config settings (the most important ones: lr, gamma and lamb_lr).
